app:
    resource: '@AppBundle/Controller/'
    type: annotation

# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: step1
        permanent: true
